### PR TITLE
fix: show episode cover for podcast

### LINKED ISSUE #309: 支持播客封面|Support podcast artwork
### Clear and concise description of the problem

大部分播客都具有单集封面，而follow选择的封面好像是音频文件的封面。图一是Apple Podcast截图，图二为follow截图

Most podcasts have individual episode covers, but it seems that the cover chosen by Follow is the audio file's cover. The first image is a screenshot from Apple Podcasts, and the second image is a screenshot from Follow.
image
image

### Suggested solution

支持播客封面
Support podcast artwork

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by hyoban**
### Description

ScreenShot 2024-09-10 11 50 21

### Linked Issues

Fixes FOL-85
Fixes #309 
https://github.com/RSSNext/follow-server/pull/73

### Additional context

Why change the dependence version?

The version in the lock file is `8.0.0`, which does not match the version in the package.json.

### CODE REVIEW

File: src/main/menu.ts [hunk 1]
```diff
@@ -87,6 +87,7 @@ export const registerAppMenu = () => {
           accelerator: "CmdOrCtrl+F",
           click(_e, window) {
             if (!window) return
+            // @ts-expect-error TODO: fix this type error
```
Comment (Innei) [inline src/main/menu.ts:90]: Remove this and rebase the upstream dev branch.

**Review by Innei — APPROVED** [review]
